version: 2
project_name: ycode
before:
  hooks:
    - go mod tidy
builds:
  - id: ycode
    main: ./cmd/ycode
    binary: ycode
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Yash-K-Jagani/ycode/cmd/ycode.Version={{.Version}}
      - -X github.com/Yash-K-Jagani/ycode/cmd/ycode.Commit={{.FullCommit}}
      - -X github.com/Yash-K-Jagani/ycode/cmd/ycode.Date={{.Date}}
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: Yash-K-Jagani
    name: ycode
